config/routes.rb
Rails.application.routes.draw do
  resources :deptmanagers
  resources :deptemps
  resources :salaries
  resources :titles
  resources :departments
  resources :employees
  
  get 'emp/:id/getemp' => 'departments#getemp', as: :emp
  
  get 'titles/:id/gettitleemp' => 'titles#gettitleemp', as: :titemp
  

end

app/models/department.rb
class Department < ActiveRecord::Base
  self.primary_key = 'dept_no'
  
  validates :dept_no, :dept_name, presence: true
  validates :dept_name, uniqueness: true
  
  has_many :dept_emps
  has_many :employees, through: :dept_emps
  
  has_many :dept_managers
  has_many :employees, through: :dept_managers  
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
	#@departments = Department.find([:d001, :d003, :d007])
	
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    
  end
  
  def getemp
    ## we will have dept id here
	@depts = Deptemp.where("dept_no = ?", params[:id])
	#deptmanager = Deptmanager.where("dept_no = ?", params[:id])
	employee = Deptmanager.find_by_dept_no(params[:id]).emp_no
	@employee_id = Employee.find_by_emp_no(employee)
  end
  
  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:dept_no, :dept_name)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dept_no %><br>
    <%= f.text_field :dept_no %>
  </div>
  <div class="field">
    <%= f.label :dept_name %><br>
    <%= f.text_field :dept_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/getemp.html.erb
<h1>Listing Employees of each Department</h1>
<h3> Department Manager</h3>
<%= @employee_id.first_name%> <%= @employee_id.last_name%>

<br> <br>

<table>
  <thead>
    <tr>
	  <th>Emp No</th>
	  <th>First Name</th>
      <th>Last Name</th>
	  <th>Salary</th>
      
    </tr>
 </thead>

  <tbody>
    <% @depts.each do |dept| %>
      <tr>
	    <td><%= dept.emp_no %></td>
        <td><%= Employee.find_by_emp_no(dept.emp_no).first_name %></td>   
	    <td><%= Employee.find_by_emp_no(dept.emp_no).last_name %></td>
		<td><%= Salarie.find_by_emp_no(dept.emp_no).salary %></td>
      </tr>
    <% end %>
	
  </tbody>
</table>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Departments</h1>

<table>
  <thead>
    <tr>
      <th>Dept no</th>
      <th>Dept name</th>
	  <th>Employees Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.dept_no %></td>
        <td><%= department.dept_name %></td>
		<% dept = department.dept_no %>
		<% empcount = Deptemp.where("dept_no = ?", dept).count %>
	    <td><%= link_to empcount, emp_url(id: department.dept_no) %>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table



<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dept no:</strong>
  <%= @department.dept_no %>
</p>

<p>
  <strong>Dept name:</strong>
  <%= @department.dept_name %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>