config/routes.rb
Rails.application.routes.draw do
  resources :deptmanagers
  resources :deptemps
  resources :salaries
  resources :titles
  resources :departments
  resources :employees
  
  get 'emp/:id/getemp' => 'departments#getemp', as: :emp
  
  get 'titles/:id/gettitleemp' => 'titles#gettitleemp', as: :titemp
  

end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  before_action :set_salary, only: [:show, :edit, :update, :destroy]

  # GET /salaries
  # GET /salaries.json
  def index
	@salaries = Salarie.all
    #@salaries = Salarie.find(['21763'])
  end

  # GET /salaries/1
  # GET /salaries/1.json
  def show
  end

  # GET /salaries/new
  def new
    @salary = Salarie.new
  end

  # GET /salaries/1/edit
  def edit
  end

  # POST /salaries
  # POST /salaries.json
  def create
    @salary = Salarie.new(salary_params)

    respond_to do |format|
      if @salary.save
        format.html { redirect_to @salary, notice: 'Salarie was successfully created.' }
        format.json { render :show, status: :created, location: @salary }
      else
        format.html { render :new }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salaries/1
  # PATCH/PUT /salaries/1.json
  def update
    respond_to do |format|
      if @salary.update(salary_params)
        format.html { redirect_to @salary, notice: 'Salarie was successfully updated.' }
        format.json { render :show, status: :ok, location: @salary }
      else
        format.html { render :edit }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salaries/1
  # DELETE /salaries/1.json
  def destroy
    @salary.destroy
    respond_to do |format|
      format.html { redirect_to salaries_url, notice: 'Salarie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salary
      @salary = Salarie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salary_params
      params.require(:salary).permit(:emp_no, :salary, :from_date, :to_date)
    end
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/views/salaries/_form.html.erb
<%= form_for(@salary) do |f| %>
  <% if @salary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salary.errors.count, "error") %> prohibited this salary from being saved:</h2>

      <ul>
      <% @salary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :emp_no %><br>
    <%= f.text_field :emp_no %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :from_date %><br>
    <%= f.date_select :from_date %>
  </div>
  <div class="field">
    <%= f.label :to_date %><br>
    <%= f.date_select :to_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salaries/edit.html.erb
<h1>Editing Salary</h1>

<%= render 'form' %>

<%= link_to 'Show', @salary %> |
<%= link_to 'Back', salaries_path %>

app/views/salaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Salaries</h1>

<table>
  <thead>
    <tr>
      <th>Emp no</th>
      <th>Salary</th>
      <th>From date</th>
      <th>To date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salaries.each do |salary| %>
      <tr>
        <td><%= salary.emp_no %></td>
        <td><%= salary.salary %></td>
        <td><%= salary.from_date %></td>
        <td><%= salary.to_date %></td>
        <td><%= link_to 'Show', salary %></td>
        <td><%= link_to 'Edit', edit_salary_path(salary) %></td>
        <td><%= link_to 'Destroy', salary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salarie', new_salary_path %>

app/views/salaries/new.html.erb
<h1>New Salary</h1>

<%= render 'form' %>

<%= link_to 'Back', salaries_path %>

app/views/salaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emp no:</strong>
  <%= @salary.emp_no %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @salary.salary %>
</p>

<p>
  <strong>From date:</strong>
  <%= @salary.from_date %>
</p>

<p>
  <strong>To date:</strong>
  <%= @salary.to_date %>
</p>

<%= link_to 'Edit', edit_salary_path(@salary) %> |
<%= link_to 'Back', salaries_path %>