config/routes.rb
Rails.application.routes.draw do
  resources :deptmanagers
  resources :deptemps
  resources :salaries
  resources :titles
  resources :departments
  resources :employees
  
  get 'emp/:id/getemp' => 'departments#getemp', as: :emp
  
  get 'titles/:id/gettitleemp' => 'titles#gettitleemp', as: :titemp
  

end

app/models/title.rb
class Title < ActiveRecord::Base
  #self.primary_keys = 'emp_no', 'title', 'from_date'
  self.primary_key = 'emp_no'
  
  validates :emp_no, :title, :from_date, :to_date, presence: true
  
  belongs_to :employee
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  before_action :set_title, only: [:show, :edit, :update, :destroy]

  # GET /titles
  # GET /titles.json
  def index
    #@titles = Title.all
	#@titles = Title.where("title = ?",'Manager')
	#@titles = Title.distinct('title')
	#@titles = Title.select(:title)
	@titles = Title.select(:title).uniq
  end

  def gettitleemp
    ## we will have title here
	@titemp = Title.where("title = ?", params[:id])
	@titname = Title.find_by_title(params[:id])
  end
  
  # GET /titles/1
  # GET /titles/1.json
  def show
  end

  # GET /titles/new
  def new
    @title = Title.new
  end

  # GET /titles/1/edit
  def edit
  end

  # POST /titles
  # POST /titles.json
  def create
    @title = Title.new(title_params)

    respond_to do |format|
      if @title.save
        format.html { redirect_to @title, notice: 'Title was successfully created.' }
        format.json { render :show, status: :created, location: @title }
      else
        format.html { render :new }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titles/1
  # PATCH/PUT /titles/1.json
  def update
    respond_to do |format|
      if @title.update(title_params)
        format.html { redirect_to @title, notice: 'Title was successfully updated.' }
        format.json { render :show, status: :ok, location: @title }
      else
        format.html { render :edit }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1
  # DELETE /titles/1.json
  def destroy
    @title.destroy
    respond_to do |format|
      format.html { redirect_to titles_url, notice: 'Title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_title
      @title = Title.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def title_params
      params.require(:title).permit(:emp_no, :title, :from_date, :to_date)
    end
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/titles/_form.html.erb
<%= form_for(@title) do |f| %>
  <% if @title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
      <% @title.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :emp_no %><br>
    <%= f.text_field :emp_no %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :from_date %><br>
    <%= f.date_select :from_date %>
  </div>
  <div class="field">
    <%= f.label :to_date %><br>
    <%= f.date_select :to_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/titles/edit.html.erb
<h1>Editing Title</h1>

<%= render 'form' %>

<%= link_to 'Show', @title %> |
<%= link_to 'Back', titles_path %>

app/views/titles/gettitleemp.html.erb
<h1>Listing Employees under Each title</h1>

<h3> Title </h3>
<%= @titname.title %>

<br> <br>

<table>
  <thead>
    <tr>
	  <th>Emp_no</th>
	  <th>First Name</th>
      <th>Last Name</th>
	  <th>Salary</th>
      
    </tr>
 </thead>

  <tbody>
    <% @titemp.each do |titl| %>
      <tr>
	    <td><%= titl.emp_no %></td>
        <td><%= Employee.find_by_emp_no(titl.emp_no).first_name %></td>   
	    <td><%= Employee.find_by_emp_no(titl.emp_no).last_name %></td>
		<td><%= Salarie.find_by_emp_no(titl.emp_no).salary %></td>
      </tr>
    <% end %>
	
  </tbody>
</table>

app/views/titles/index.html - Copy (2).erb
<p id="notice"><%= notice %></p>

<h1>Listing Titles</h1>

<table>
  <thead>
    <tr>      
   	  <th>Title Count</th>	  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @titles.each do |title| %>
      <tr>
        <td><% title.emp_no %></td>
        <td><% title.title%></td>
		<td><%= Title.where("title = ? ",title.title).count %></td>
        <td><% title.from_date %></td>
        <td><% title.to_date %></td>
        <td><%= link_to 'Show', title %></td>
        <td><%= link_to 'Edit', edit_title_path(title) %></td>
        <td><%= link_to 'Destroy', title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Title', new_title_path %>

app/views/titles/index.html - Copy.erb
<p id="notice"><%= notice %></p>

<h1>Listing Titles</h1>

<table>
  <thead>
    <tr>
      <th>Emp no</th>
      <th>Title</th>
      <th>From date</th>
      <th>To date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @titles.each do |title| %>
      <tr>
        <td><%= title.emp_no %></td>
        <td><%= title.title %></td>
        <td><%= title.from_date %></td>
        <td><%= title.to_date %></td>
        <td><%= link_to 'Show', title %></td>
        <td><%= link_to 'Edit', edit_title_path(title) %></td>
        <td><%= link_to 'Destroy', title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% dept = department.dept_no %>
	    <td><%= link_to Deptemp.where("dept_no = ?", dept).count, emp_url(id: department.dept_no) %>

<br>

<%= link_to 'New Title', new_title_path %>

app/views/titles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Titles</h1>

<table>
  <thead>
    <tr>
     
      <th>Title</th>
	  <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @titles.each do |title| %>
      <tr>
        
        <td><%= title.title %></td>
		<td><%= link_to Title.where(title: title.title).count, titemp_url(id: title.title) %></td>
 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Title', new_title_path %>

app/views/titles/index.html.v1.erb
<p id="notice"><%= notice %></p>

<h1>Listing Titles</h1>

<table>
  <thead>
    <tr>      
   	  <th>Title Count</th>	  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @titles.each do |title| %>
      <tr>
        <td><% title.emp_no %></td>
        <td><% title.title%></td>
		<td><%= Title.where("title = ? ",title.title).count %></td>
        <td><% title.from_date %></td>
        <td><% title.to_date %></td>
        <td><%= link_to 'Show', title %></td>
        <td><%= link_to 'Edit', edit_title_path(title) %></td>
        <td><%= link_to 'Destroy', title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Title', new_title_path %>

app/views/titles/new.html.erb
<h1>New Title</h1>

<%= render 'form' %>

<%= link_to 'Back', titles_path %>

app/views/titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emp no:</strong>
  <%= @title.emp_no %>
</p>

<p>
  <strong>Title:</strong>
  <%= @title.title %>
</p>

<p>
  <strong>From date:</strong>
  <%= @title.from_date %>
</p>

<p>
  <strong>To date:</strong>
  <%= @title.to_date %>
</p>

<%= link_to 'Edit', edit_title_path(@title) %> |
<%= link_to 'Back', titles_path %>